name: Playwright Tests
on:
  workflow_dispatch:
    inputs:
      IFramesTabsAndWindowsTests:
        description: 'IFrames and Tabs/Windows tests on Way2Automation'
        required: false
        type: boolean
        default: false

      EnvironmentVariableTests:
        description: 'Test showcasing usage of Environment Variables. If selected, pick Environment Variables below'
        required: false
        type: boolean
        default: false

      EnvironmentVariables:
        description: 'Environment Variables for EnvironmentVariableTests'
        required: false
        type: choice
        options:
          - ExpandTesting.com
          - PracticeTestAutomation.com

  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*

    - name: Install dependencies
      run: npm ci

    - name: Install Playwright Browsers
      run: npx playwright install --with-deps

    - name: Determine test tags to run
      run: |
        TAGS=""
        if [ "${{ inputs.IFramesTabsAndWindowsTests }}" = "true" ]; then
          TAGS="${TAGS}@Way2AutomationFrameTests|"
        fi
        if [ "${{ inputs.EnvironmentVariableTests }}" = "true" ]; then
          TAGS="${TAGS}@EnvVariableTest|"
        fi
        if [ -n "$TAGS" ]; then
          TAGS="${TAGS::-1}"
        fi
        echo "TEST_TAGS=$TAGS" >> $GITHUB_ENV

    - name: Set environment variables for environment variable tests
      run: |
        if [ "${{ github.event_name != 'workflow_dispatch' }}" ] || [ "${{ inputs.EnvironmentVariables == 'ExpandTesting.com' }}" ]; then
          echo "TEST_USERNAME=${{ secrets.EXPANDTESTING_USERNAME }}" >> $GITHUB_ENV
          echo "TEST_PASSWORD=${{ secrets.EXPANDTESTING_PASSWORD }}" >> $GITHUB_ENV
          echo "TEST_URL=${{ vars.EXPANDTESTING_URL }}" >> $GITHUB_ENV
        fi
        if [ "${{ inputs.EnvironmentVariables == 'PracticeTestAutomation.com' }}" ]; then
          echo "TEST_USERNAME=${{ secrets.PRACTICETESTAUTOMATION_USERNAME }}" >> $GITHUB_ENV
          echo "TEST_PASSWORD=${{ secrets.PRACTICETESTAUTOMATION_PASSWORD }}" >> $GITHUB_ENV
          echo "TEST_URL=${{ vars.PRACTICETESTAUTOMATION_URL }}" >> $GITHUB_ENV
        fi

    - name: Run Playwright tests
      run: |
        if [ -z "${{ env.TEST_TAGS }}" = "true" ]; then
          npx playwright test
        else
          npx playwright test --grep "${{ env.TEST_TAGS }}"
        fi
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 10
