name: Playwright Tests
on:
  workflow_dispatch:
    inputs:
      openNewBrowserTab:
        description: 'Open New Browser Tab Test'
        required: false
        type: boolean
        default: false

      openNewSeparateWindow:
        description: 'Open New Separate Window Test'
        required: false
        type: boolean
        default: false

      openNewFramesetTab:
        description: 'Open New Frameset Tab Test'
        required: false
        type: boolean
        default: false

      openMultipleNewWindows:
        description: 'Open Multiple New Windows Test'
        required: false
        type: boolean
        default: false

  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*

    - name: Install dependencies
      run: npm ci

    - name: Install Playwright Browsers
      run: npx playwright install --with-deps

    - name: Determine tags to run
      run: |
        TAGS=""
        if [ "${{ inputs.openNewBrowserTab }}" = "true" ]; then
          TAGS="${TAGS}@OpenNewBrowserTab|"
        fi
        if [ "${{ inputs.openNewSeparateWindow }}" = "true" ]; then
          TAGS="${TAGS}@OpenNewSeparateWindow|"
        fi
        if [ "${{ inputs.openNewFramesetTab }}" = "true" ]; then
          TAGS="${TAGS}@OpenNewFramesetTab|"
        fi
        if [ "${{ inputs.openMultipleNewWindows }}" = "true" ]; then
          TAGS="${TAGS}@OpenMultipleNewWindows|"
        fi
        if [ -n "$TAGS" ]; then
          TAGS="${TAGS::-1}"
        fi
        echo "TEST_TAGS=$TAGS" >> $GITHUB_ENV

    - name: Log the inputs
      run: |
        echo "TAGS: ${{ env.TEST_TAGS }}"

    - name: Run Playwright tests
      run: |
        if [ -z "${{ env.TEST_TAGS }}" = "true" ]; then
          npx playwright test
        else
          npx playwright test --grep "${{ env.TEST_TAGS }}"
        fi
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 10
